drop table if exists adress cascade;
create table adress (
    id_adress bigint generated by default as identity,
    bairro varchar(255),
    cep varchar(255),
    complemento varchar(255),
    localidade varchar(255),
    logradouro varchar(255),
    uf varchar(255),
    user_id bigint not null,
    primary key (id_adress)
);

drop table if exists categories cascade;
create table categories (
    id_categories bigint not null,
    categories varchar(255)
);

drop table if exists authors cascade;
create table authors (
   id_authors bigint not null,
    authors varchar(255)
);

drop table if exists book cascade;
create table book (
   id_book bigint generated by default as identity,
    self_link varchar(255),
    id_book_info bigint not null,
    primary key (id_book)
);

drop table if exists book_info cascade;
create table book_info (
    id_book_info bigint generated by default as identity,
    canonical_volume_link varchar(255),
    description varchar(1000),
    info_link varchar(255),
    preview_link varchar(255),
    publisher_date varchar(255),
    publisher varchar(255),
    text_snippet varchar(255),
    title varchar(255),
    id_image_links bigint,
    primary key (id_book_info)
);

drop table if exists donation cascade;
create table donation (
   id_donation bigint generated by default as identity,
    status integer,
    book_id bigint not null,
    id_user bigint not null,
    primary key (id_donation)
);

drop table if exists image_links cascade;
create table image_links (
    id_image_links bigint generated by default as identity,
    small_thumbnail varchar(255),
    thumbnail varchar(255),
    primary key (id_image_links)
);

drop table if exists users cascade;
create table users (
    id_user bigint generated by default as identity,
    email varchar(255),
    password varchar(255),
    phone varchar(255),
    username varchar(255),
    primary key (id_user)
);
